export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_ON_SEARCH = "FETCH_ON_SEARCH";

export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_ON_SEARCH_SUCCESS = "FETCH_ON_SEARCH_SUCCESS";

export const FETCH_START = "FETCH_START";
export const FETCH_FAIL = "FETCH_FAIL";
